# World Energy Transition 2000–2025
- Build a story around the global shift from fossil fuels to renewable energy.
- The dataset contains information about the global renewable energy transition from 2000 to 2025.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("global_renewable_energy_transition_2000_2025.csv") # Load the dataset

In [3]:
print("Dataset Shape : ", df.shape[0],"rows, ",df.shape[1],"columns")
print("Countries     : ", df['country'].nunique())
print("Regions       : ", df['region'].nunique())
print("Years         : ", df['year'].min(), " - ", df['year'].max())

pd.set_option('display.max_columns', None)
df.head(5)

Dataset Shape :  1294 rows,  25 columns
Countries     :  50
Regions       :  8
Years         :  2000  -  2025

,country,region,income_group,year,population,gdp_usd,total_electricity_generation_twh,electricity_demand_twh,solar_electricity_twh,wind_electricity_twh,renewables_electricity_twh,hydro_electricity_twh,nuclear_electricity_twh,fossil_electricity_twh,solar_share_pct,wind_share_pct,renewables_share_pct,fossil_share_pct,low_carbon_share_pct,carbon_intensity_gco2_kwh,co2_saved_solar_wind_mt,solar_yoy_growth_pct,wind_yoy_growth_pct,renewables_yoy_growth_pct,policy_milestone
0,Algeria,Africa,Lower-middle,2000,30903894.0,2.085542e+11,25.40,25.33,0.0,0.0,0.05,0.05,0.0,25.35,0.0,0.0,0.197,99.803,0.197,638.58,0.0,NaN,NaN,NaN,NaN
1,Algeria,Africa,Lower-middle,2001,31331226.0,2.234203e+11,26.62,26.57,0.0,0.0,0.07,0.07,0.0,26.55,0.0,0.0,0.263,99.737,0.263,638.24,0.0,NaN,NaN,40.0,NaN
2,Algeria,Africa,Lower-middle,2002,31750832.0,2.453609e+11,27.65,27.63,0.0,0.0,0.06,0.06,0.0,27.59,0.0,0.0,0.217,99.783,0.217,637.98,0.0,NaN,NaN,-14.3,NaN
3,Algeria,Africa,Lower-middle,2003,32175813.0,2.735686e+11,29.57,29.58,0.0,0.0,0.26,0.26,0.0,29.31,0.0,0.0,0.879,99.121,0.879,634.09,0.0,NaN,NaN,333.3,NaN
4,Algeria,Africa,Lower-middle,2004,32628286.0,2.967736e+11,31.25,31.26,0.0,0.0,0.25,0.25,0.0,31.00,0.0,0.0,0.800,99.200,0.800,634.56,0.0,NaN,NaN,-3.8,NaN

In [4]:
# Column-level data dictionary
col_info = {
    'country':                         'Country name',
    'region':                          'World region classification',
    'income_group':                    'World Bank income category',
    'year':                            'Observation year (2000–2025)',
    'population':                      'Total population',
    'gdp_usd':                         'GDP in current USD',
    'total_electricity_generation_twh':'Total electricity generated (TWh)',
    'electricity_demand_twh':          'Electricity consumed (TWh)',
    'solar_electricity_twh':           'Solar PV generation (TWh)',
    'wind_electricity_twh':            'Wind generation (TWh)',
    'renewables_electricity_twh':      'All renewables generation (TWh)',
    'hydro_electricity_twh':           'Hydropower generation (TWh)',
    'nuclear_electricity_twh':         'Nuclear generation (TWh)',
    'fossil_electricity_twh':          'Fossil fuel generation (TWh)',
    'solar_share_pct':                 'Solar as % of total generation',
    'wind_share_pct':                  'Wind as % of total generation',
    'renewables_share_pct':            'All renewables as % of total generation',
    'fossil_share_pct':                'Fossils as % of total generation',
    'low_carbon_share_pct':            'Low-carbon (renewables + nuclear) % share',
    'carbon_intensity_gco2_kwh':       'gCO₂ emitted per kWh generated',
    'co2_saved_solar_wind_mt':         'CO₂ avoided by solar + wind (Mt)',
    'solar_yoy_growth_pct':            'Year-on-year solar growth (%)',
    'wind_yoy_growth_pct':             'Year-on-year wind growth (%)',
    'renewables_yoy_growth_pct':       'Year-on-year renewables growth (%)',
    'policy_milestone':                'Notable national energy policy milestone',
}

pd.DataFrame.from_dict(col_info, orient='index', columns=['Description']).rename_axis('Column')

                                                                Description
Column
country                                                        Country name
region                                          World region classification
income_group                                     World Bank income category
year                                           Observation year (2000–2025)
population                                                 Total population
gdp_usd                                                  GDP in current USD
total_electricity_generation_twh          Total electricity generated (TWh)
electricity_demand_twh                           Electricity consumed (TWh)
solar_electricity_twh                             Solar PV generation (TWh)
wind_electricity_twh                                  Wind generation (TWh)
renewables_electricity_twh                  All renewables generation (TWh)
hydro_electricity_twh                           Hydropower generation (TWh)
nuclear_electricity_twh                            Nuclear generation (TWh)
fossil_electricity_twh                         Fossil fuel generation (TWh)
solar_share_pct                              Solar as % of total generation
wind_share_pct                                Wind as % of total generation
renewables_share_pct                All renewables as % of total generation
fossil_share_pct                           Fossils as % of total generation
low_carbon_share_pct              Low-carbon (renewables + nuclear) % share
carbon_intensity_gco2_kwh                    gCO₂ emitted per kWh generated
co2_saved_solar_wind_mt                    CO₂ avoided by solar + wind (Mt)
solar_yoy_growth_pct                          Year-on-year solar growth (%)
wind_yoy_growth_pct                            Year-on-year wind growth (%)
renewables_yoy_growth_pct                Year-on-year renewables growth (%)
policy_milestone                   Notable national energy policy milestone

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1294 entries, 0 to 1293
Data columns (total 25 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   country                           1294 non-null   str
 1   region                            1294 non-null   str
 2   income_group                      1294 non-null   str
 3   year                              1294 non-null   int64
 4   population                        1294 non-null   float64
 5   gdp_usd                           1150 non-null   float64
 6   total_electricity_generation_twh  1294 non-null   float64
 7   electricity_demand_twh            1294 non-null   float64
 8   solar_electricity_twh             1294 non-null   float64
 9   wind_electricity_twh              1262 non-null   float64
 10  renewables_electricity_twh        1294 non-null   float64
 11  hydro_electricity_twh             1218 non-null   float64
 12  nuclear_electricity_twh           1288 non-null   float64
 13  fossil_electricity_twh            1294 non-null   float64
 14  solar_share_pct                   1294 non-null   float64
 15  wind_share_pct                    1262 non-null   float64
 16  renewables_share_pct              1294 non-null   float64
 17  fossil_share_pct                  1294 non-null   float64
 18  low_carbon_share_pct              1294 non-null   float64
 19  carbon_intensity_gco2_kwh         1294 non-null   float64
 20  co2_saved_solar_wind_mt           1294 non-null   float64
 21  solar_yoy_growth_pct              872 non-null    float64
 22  wind_yoy_growth_pct               964 non-null    float64
 23  renewables_yoy_growth_pct         1214 non-null   float64
 24  policy_milestone                  59 non-null     str
dtypes: float64(20), int64(1), str(4)
memory usage: 283.7 KB

In [6]:
gdp_null = df[df['gdp_usd'].isna()]

sns

In [24]:
df.isna().sum()

country                              0
region                               0
income_group                         0
year                                 0
population                           0
gdp_usd                              0
total_electricity_generation_twh     0
electricity_demand_twh               0
solar_electricity_twh                0
wind_electricity_twh                 6
renewables_electricity_twh           0
hydro_electricity_twh               76
nuclear_electricity_twh              0
fossil_electricity_twh               0
solar_share_pct                      0
wind_share_pct                       6
renewables_share_pct                 0
fossil_share_pct                     0
low_carbon_share_pct                 0
carbon_intensity_gco2_kwh            0
co2_saved_solar_wind_mt              0
solar_yoy_growth_pct                 0
wind_yoy_growth_pct                  0
renewables_yoy_growth_pct            0
policy_milestone                     0
dtype: int64

In [23]:
# Datatypes and null values check
null_summary = df.isna().sum().rename('Missing').to_frame()
null_summary['% Missing'] = (null_summary['Missing'] / len(df) * 100).round(2)
null_summary['DTypes'] = df.dtypes
null_summary[null_summary['Missing'] > 0].sort_values('Missing', ascending=False)

                       Missing  % Missing   DTypes
hydro_electricity_twh       76       5.87  float64
wind_electricity_twh         6       0.46  float64
wind_share_pct               6       0.46  float64

In [9]:
len(df[(df['gdp_usd'].isna()) & (df['year'].isin([2023, 2024, 2025]))])

144

In [10]:
nan_gdp_df = df[df['gdp_usd'].isna()]

nan_gdp_df['year'].value_counts()

year
2023    50
2024    50
2025    44
Name: count, dtype: int64

In [11]:
# check for duplicate rows in the dataset

dupes = df.duplicated().sum()
print(f"Duplicates: {dupes}")
# If country + year should be unique:
if df.duplicated(subset=['country', 'year']).sum() > 0:
    df = df.drop_duplicates(subset=['country', 'year'])

Duplicates: 0

## Handling Missing Values

#### Replace inf values with NaN

In [12]:
np.isinf(df.select_dtypes(include='number')).sum() # find all 'inf' values

year                                 0
population                           0
gdp_usd                              0
total_electricity_generation_twh     0
electricity_demand_twh               0
solar_electricity_twh                0
wind_electricity_twh                 0
renewables_electricity_twh           0
hydro_electricity_twh                0
nuclear_electricity_twh              0
fossil_electricity_twh               0
solar_share_pct                      0
wind_share_pct                       0
renewables_share_pct                 0
fossil_share_pct                     0
low_carbon_share_pct                 0
carbon_intensity_gco2_kwh            0
co2_saved_solar_wind_mt              0
solar_yoy_growth_pct                36
wind_yoy_growth_pct                 28
renewables_yoy_growth_pct            3
dtype: int64

In [13]:
# Replace inf with NaN in growth rate columns

growth_cols = ['solar_yoy_growth_pct', 'wind_yoy_growth_pct', 'renewables_yoy_growth_pct']

for col in growth_cols:
    df[col] = df[col].replace([np.inf, -np.inf], np.nan)

In [14]:
np.isinf(df.select_dtypes(include='number')).sum()

year                                0
population                          0
gdp_usd                             0
total_electricity_generation_twh    0
electricity_demand_twh              0
solar_electricity_twh               0
wind_electricity_twh                0
renewables_electricity_twh          0
hydro_electricity_twh               0
nuclear_electricity_twh             0
fossil_electricity_twh              0
solar_share_pct                     0
wind_share_pct                      0
renewables_share_pct                0
fossil_share_pct                    0
low_carbon_share_pct                0
carbon_intensity_gco2_kwh           0
co2_saved_solar_wind_mt             0
solar_yoy_growth_pct                0
wind_yoy_growth_pct                 0
renewables_yoy_growth_pct           0
dtype: int64

#### Impute missing GDP values with country-specific mean

In [15]:
df['gdp_usd'] = df.groupby('country')['gdp_usd'].transform(
    lambda x: x.fillna(x.mean())
)

In [16]:
# --------------------------------------------------
# 1. Wind generation and share
# Countries with no wind generation -> fill with 0
# --------------------------------------------------
no_wind = (
    df.groupby('country')['wind_electricity_twh']
    .transform('sum')
    .fillna(0)
    .eq(0)
)

df.loc[no_wind & df['wind_electricity_twh'].isna(),
           'wind_electricity_twh'] = 0

df.loc[no_wind & df['wind_share_pct'].isna(),
           'wind_share_pct'] = 0

In [17]:
# --------------------------------------------------
# 2. Hydro & Nuclear generation
# Interpolate within each country over time
# --------------------------------------------------
for col in ['hydro_electricity_twh', 'nuclear_electricity_twh']:
    df[col] = (
        df.sort_values('year')
        .groupby('country')[col]
        .transform(lambda x: x.interpolate(limit_direction='both'))
    )

In [18]:
# --------------------------------------------------
# 3. Growth columns
# Calculate from previous year if possible
# --------------------------------------------------
for col in [
    'solar_yoy_growth_pct',
    'wind_yoy_growth_pct',
    'renewables_yoy_growth_pct'
]:
    df[col] = (
        df.groupby('country')[col]
        .transform(lambda x: x.interpolate(limit_direction='both'))
    )

In [19]:
# Remaining missing values -> median
growth_cols = [
    'solar_yoy_growth_pct',
    'wind_yoy_growth_pct',
    'renewables_yoy_growth_pct'
]

for col in growth_cols:
    df[col] = df[col].fillna(df[col].median())

In [20]:
# --------------------------------------------------
# 4. Policy milestone
# Missing means no recorded policy
# --------------------------------------------------
df['policy_milestone'] = (
    df['policy_milestone']
    .fillna('No recorded policy')
)

In [21]:
df['hydro_electricity_twh'] = (
    df.groupby('country')['hydro_electricity_twh']
      .transform(lambda x: x.interpolate(limit_direction='both'))
)

In [27]:
df.isna().sum()

country                              0
region                               0
income_group                         0
year                                 0
population                           0
gdp_usd                              0
total_electricity_generation_twh     0
electricity_demand_twh               0
solar_electricity_twh                0
wind_electricity_twh                 6
renewables_electricity_twh           0
hydro_electricity_twh               76
nuclear_electricity_twh              0
fossil_electricity_twh               0
solar_share_pct                      0
wind_share_pct                       6
renewables_share_pct                 0
fossil_share_pct                     0
low_carbon_share_pct                 0
carbon_intensity_gco2_kwh            0
co2_saved_solar_wind_mt              0
solar_yoy_growth_pct                 0
wind_yoy_growth_pct                  0
renewables_yoy_growth_pct            0
policy_milestone                     0
dtype: int64

In [28]:
temp_df = df[df['hydro_electricity_twh'].isna()]

temp_df['country'].value_counts()

country
Singapore               26
Saudi Arabia            25
United Arab Emirates    25
Name: count, dtype: int64

In [29]:
# Since these countries effectively have no hydro generation, filling with 0 is reasonable:

no_hydro_countries = [
    'Singapore',
    'Saudi Arabia',
    'United Arab Emirates'
]

mask = (
    df['country'].isin(no_hydro_countries)
    & df['hydro_electricity_twh'].isna()
)

df.loc[mask, 'hydro_electricity_twh'] = 0

In [31]:
df[df['wind_electricity_twh'].isna()][['country', 'year']]

     country  year
286  Czechia  2001
855  Romania  2000
856  Romania  2001
857  Romania  2002
858  Romania  2003
859  Romania  2004

In [33]:
df['wind_electricity_twh'] = df['wind_electricity_twh'].fillna(0)
df['wind_share_pct'] = df['wind_share_pct'].fillna(0)

In [34]:
df.isna().sum()

country                             0
region                              0
income_group                        0
year                                0
population                          0
gdp_usd                             0
total_electricity_generation_twh    0
electricity_demand_twh              0
solar_electricity_twh               0
wind_electricity_twh                0
renewables_electricity_twh          0
hydro_electricity_twh               0
nuclear_electricity_twh             0
fossil_electricity_twh              0
solar_share_pct                     0
wind_share_pct                      0
renewables_share_pct                0
fossil_share_pct                    0
low_carbon_share_pct                0
carbon_intensity_gco2_kwh           0
co2_saved_solar_wind_mt             0
solar_yoy_growth_pct                0
wind_yoy_growth_pct                 0
renewables_yoy_growth_pct           0
policy_milestone                    0
dtype: int64

## Encoding Categorical Columns

In [37]:
df.select_dtypes(include='str').columns

Index(['country', 'region', 'income_group', 'policy_milestone'], dtype='str')

In [40]:
# creating flag column for policy_milestone

df['has_policy_milestone'] = df['policy_milestone'].notna().astype(int)

# df.drop(columns=['policy_milestone'], inplace=True)

### Encoding Income Group Column

In [42]:
df['income_group'].unique()

<ArrowStringArray>
['Lower-middle', 'Upper-middle', 'High']
Length: 3, dtype: str

In [44]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[['Lower-middle', 'Upper-middle', 'High']])

df['income_group_encoded'] = encoder.fit_transform(df[['income_group']])

### Encode country and region using Label Encoding

In [ ]:
# Encode country and region using Label Encoding

from sklearn.preprocessing import LabelEncoder

le_country = LabelEncoder()
df['country_encoded'] = le_country.fit_transform(df['country'])

le_region = LabelEncoder()
df['region_encoded'] = le_region.fit_transform(df['region'])

In [48]:
df.drop(columns=['country', 'region', 'income_group', 'policy_milestone'], inplace=True)

In [49]:
df.head()

,year,population,gdp_usd,total_electricity_generation_twh,electricity_demand_twh,solar_electricity_twh,wind_electricity_twh,renewables_electricity_twh,hydro_electricity_twh,nuclear_electricity_twh,fossil_electricity_twh,solar_share_pct,wind_share_pct,renewables_share_pct,fossil_share_pct,low_carbon_share_pct,carbon_intensity_gco2_kwh,co2_saved_solar_wind_mt,solar_yoy_growth_pct,wind_yoy_growth_pct,renewables_yoy_growth_pct,has_policy_milestone,income_group_encoded,country_encoded,region_encoded
0,2000,30903894.0,2.085542e+11,25.40,25.33,0.0,0.0,0.05,0.05,0.0,25.35,0.0,0.0,0.197,99.803,0.197,638.58,0.0,50.0,50.0,40.0,1,0.0,0,0
1,2001,31331226.0,2.234203e+11,26.62,26.57,0.0,0.0,0.07,0.07,0.0,26.55,0.0,0.0,0.263,99.737,0.263,638.24,0.0,50.0,50.0,40.0,1,0.0,0,0
2,2002,31750832.0,2.453609e+11,27.65,27.63,0.0,0.0,0.06,0.06,0.0,27.59,0.0,0.0,0.217,99.783,0.217,637.98,0.0,50.0,50.0,-14.3,1,0.0,0,0
3,2003,32175813.0,2.735686e+11,29.57,29.58,0.0,0.0,0.26,0.26,0.0,29.31,0.0,0.0,0.879,99.121,0.879,634.09,0.0,50.0,50.0,333.3,1,0.0,0,0
4,2004,32628286.0,2.967736e+11,31.25,31.26,0.0,0.0,0.25,0.25,0.0,31.00,0.0,0.0,0.800,99.200,0.800,634.56,0.0,50.0,50.0,-3.8,1,0.0,0,0

In [50]:
df.describe()

,year,population,gdp_usd,total_electricity_generation_twh,electricity_demand_twh,solar_electricity_twh,wind_electricity_twh,renewables_electricity_twh,hydro_electricity_twh,nuclear_electricity_twh,fossil_electricity_twh,solar_share_pct,wind_share_pct,renewables_share_pct,fossil_share_pct,low_carbon_share_pct,carbon_intensity_gco2_kwh,co2_saved_solar_wind_mt,solar_yoy_growth_pct,wind_yoy_growth_pct,renewables_yoy_growth_pct,has_policy_milestone,income_group_encoded,country_encoded,region_encoded
count,1294.000000,1.294000e+03,1.294000e+03,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.000000,1294.0,1294.000000,1294.000000,1294.000000
mean,2012.442040,1.125009e+08,1.705678e+12,421.907087,422.052233,9.318253,16.417743,98.048153,63.686074,50.056553,273.802380,1.545879,2.712126,26.575321,63.783165,36.216834,478.219629,11.581012,252.928053,107.752859,13.203246,1.0,1.380989,24.487635,2.757342
std,7.471687,2.571628e+08,3.196584e+12,1005.866867,1006.426126,51.811846,70.629395,262.073928,150.584851,131.609128,688.528146,3.266796,5.000763,25.377875,29.798675,29.798675,236.357492,53.989109,954.013119,427.996618,51.360450,0.0,0.745791,14.423581,2.063907
min,2000.000000,1.954713e+06,7.105397e+10,15.940000,15.940000,0.000000,0.000000,0.000000,0.000000,0.000000,0.410000,0.000000,0.000000,0.000000,0.288000,0.000000,25.750000,0.000000,-94.000000,-100.000000,-60.000000,1.0,0.000000,0.000000,0.000000
25%,2006.000000,1.707635e+07,3.579440e+11,72.890000,72.590000,0.000000,0.010000,8.612500,3.672500,0.000000,38.147500,0.000000,0.003000,7.369000,41.612000,11.275250,291.087500,0.020000,3.925000,0.000000,-1.400000,1.0,1.000000,12.000000,1.000000
50%,2012.000000,3.841923e+07,7.128637e+11,141.080000,137.475000,0.080000,0.590000,30.600000,17.680000,0.000000,89.520000,0.041000,0.286500,17.086000,69.246000,30.754000,510.070000,0.550000,34.050000,16.700000,5.400000,1.0,2.000000,24.500000,2.000000
75%,2019.000000,8.696030e+07,1.628240e+12,307.467500,328.145000,2.537500,6.767500,82.995000,49.515000,34.400000,194.915000,1.488000,3.121250,40.704500,88.724750,58.388000,650.002500,4.870000,133.300000,50.000000,14.925000,1.0,2.000000,37.000000,4.000000
max,2025.000000,1.463866e+09,2.696602e+13,10583.360000,10563.900000,1174.960000,1135.440000,3920.470000,1397.060000,809.410000,6237.200000,25.062000,29.366000,99.712000,100.000000,99.712000,1150.480000,1039.680000,24000.000000,7800.000000,1124.500000,1.0,2.000000,49.000000,7.000000

## Country Column
 - 50 countries

In [ ]:
num_of_country = df['country'].nunique()
print(num_of_country)

country_list = df['country'].unique().tolist()

print(country_list)

## region column
- most records are from Europe and Asia

In [ ]:
df["region"].value_counts() # Region wise data records

In [ ]:
# Region wise Countries

region_countries = df.groupby("region")["country"].unique()

for region, countries in region_countries.items():
    print(f"\n{region}:")
    for country in countries:
        print(f"  - {country}")

# Income group column

In [ ]:
df['income_group'].value_counts()

In [ ]:
df[df['policy_milestone'].notna()].sample(8)

In [ ]:
df["policy_milestone"].nunique()

In [ ]:
df[df['solar_yoy_growth_pct'] == np.inf].head()

In [ ]:
df[(df['country'] == 'Bangladesh') & (df['year'] == 2005)]

In [ ]:
country_gdp = df.groupby('country')['gdp_usd'].mean()
country_gdp.nlargest(10).plot(kind='barh')
plt.title("Top 10 Countries by Average GDP")
plt.show()

In [ ]:
np.isinf(df.select_dtypes(include='number')).sum()

In [26]:
temp_df = df[df['hydro_electricity_twh'].isna()]

temp_df['country'].value_counts()

country
Singapore               26
Saudi Arabia            25
United Arab Emirates    25
Name: count, dtype: int64