# Cleaning Data with Pandas

In [1]:
import pandas as pd

In [44]:
# Load the data using pandas
df = pd.read_csv("messy_employee_dataset.csv")

In [45]:
# Know your data
df.head(3)

    Name   Age Department       City
0   Amit  24.0         ML  Ahmedabad
1    NaN  23.0      Sales     Rajkot
2  Karan  24.0         AI     Rajkot

In [46]:
# Get number of rows and columns
df.shape

(30, 4)

In [47]:
# Get data types of each column and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        28 non-null     str
 1   Age         23 non-null     float64
 2   Department  29 non-null     str
 3   City        25 non-null     str
dtypes: float64(1), str(3)
memory usage: 1.5 KB

In [48]:
df.describe()

             Age
count  23.000000
mean   23.608696
std     1.305204
min    21.000000
25%    23.000000
50%    24.000000
75%    25.000000
max    25.000000

In [49]:
# Check for Null Values in Columns
df.isna().sum()

Name          2
Age           7
Department    1
City          5
dtype: int64

In [50]:
# Check for duplicate rows in Data
df[df.duplicated()]

Empty DataFrame
Columns: [Name, Age, Department, City]
Index: []

## Cleaning Data

In [51]:
df[df["Name"].isna()]

  Name   Age Department      City
1  NaN  23.0      Sales    Rajkot
6  NaN  24.0        NaN  Vadodara

In [52]:
df["Name"] = df["Name"].fillna("Unknown")  # Null name filled with 'Unknown'

df[df["Name"].isna()]

Empty DataFrame
Columns: [Name, Age, Department, City]
Index: []

In [53]:
# Department column

df[df["Department"].isna()]

      Name   Age Department      City
6  Unknown  24.0        NaN  Vadodara

In [54]:
df = df.dropna(subset=["Department"])  # Drop rows where Department is null

In [55]:
df[df["Department"].isna()]

Empty DataFrame
Columns: [Name, Age, Department, City]
Index: []

In [56]:
df = df.reset_index(drop=True) # Reset index after dropping rows

In [57]:
# cleaning age column
median_age = df["Age"].median()

print(median_age)
print()

df["Age"] = df["Age"].fillna(median_age)

24.0

In [58]:
# cleaning City column

df["City"].value_counts()

City
Vadodara     9
Ahmedabad    8
Rajkot       5
Surat        2
Name: count, dtype: int64

In [59]:
most_frequent_city = df["City"].mode()[0]
most_frequent_city

'Vadodara'

In [60]:
df["City"] = df["City"].fillna(most_frequent_city)

In [61]:
df.isna().sum()

Name          0
Age           0
Department    0
City          0
dtype: int64

In [62]:
# Final Cleaned Data
print(df.to_string())

       Name   Age Department       City
0      Amit  24.0         ML  Ahmedabad
1   Unknown  23.0      Sales     Rajkot
2     Karan  24.0         AI     Rajkot
3     Karan  23.0      Sales   Vadodara
4    Simran  21.0         ML   Vadodara
5      Neha  25.0    Support     Rajkot
6       Raj  24.0         AI      Surat
7     Karan  25.0    Support   Vadodara
8    Simran  24.0         AI   Vadodara
9      Neha  24.0    Support     Rajkot
10     Riya  24.0         AI   Vadodara
11      Jay  25.0         HR   Vadodara
12     Riya  25.0         ML  Ahmedabad
13      Raj  22.0         HR     Rajkot
14   Simran  25.0         AI   Vadodara
15     Amit  23.0         AI  Ahmedabad
16      Jay  24.0         AI   Vadodara
17     Riya  24.0      Sales   Vadodara
18      Raj  23.0         ML   Vadodara
19     Riya  25.0         AI  Ahmedabad
20    Karan  25.0      Sales  Ahmedabad
21     Riya  24.0         AI      Surat
22     Amit  24.0         AI  Ahmedabad
23     Neha  24.0         AI  Ahmedabad
24     Amit  24.0         ML   Vadodara
25   Simran  22.0    Support   Vadodara
26      Raj  24.0         HR  Ahmedabad
27      Jay  21.0    Support   Vadodara
28    Priya  22.0         AI   Vadodara

## --> Grouping and Aggregation in Pandas

- df.groupby("column").agg(function)

In [67]:
df.groupby("City")["Age"].mean()

City
Ahmedabad    24.250000
Rajkot       23.600000
Surat        24.000000
Vadodara     23.357143
Name: Age, dtype: float64

In [68]:
df.groupby("City")["Name"].count()

City
Ahmedabad     8
Rajkot        5
Surat         2
Vadodara     14
Name: Name, dtype: int64

In [69]:
df.nunique()  # Unique values count in each column

Name          9
Age           5
Department    5
City          4
dtype: int64

In [71]:
df["Name"].value_counts()

Name
Riya       5
Amit       4
Karan      4
Simran     4
Raj        4
Neha       3
Jay        3
Unknown    1
Priya      1
Name: count, dtype: int64

In [74]:
# Sorting values in Columns

df.sort_values("Age").head(10)

       Name   Age Department       City
4    Simran  21.0         ML   Vadodara
27      Jay  21.0    Support   Vadodara
25   Simran  22.0    Support   Vadodara
13      Raj  22.0         HR     Rajkot
28    Priya  22.0         AI   Vadodara
15     Amit  23.0         AI  Ahmedabad
3     Karan  23.0      Sales   Vadodara
1   Unknown  23.0      Sales     Rajkot
18      Raj  23.0         ML   Vadodara
9      Neha  24.0    Support     Rajkot