In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_train = pd.read_csv("train.csv")

In [3]:
X = df_train.drop("Rented Bike Count", axis=1)
y = df_train["Rented Bike Count"]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [6]:
from sklearn.ensemble import AdaBoostRegressor

abr = AdaBoostRegressor(n_estimators=80, learning_rate=0.01)

from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor()

In [7]:
abr.fit(X_train, y_train)
y_pred_abr = abr.predict(X_test)

gbr.fit(X_train, y_train)
y_pred_gbr = gbr.predict(X_test)

In [9]:
from xgboost import XGBRegressor

xgbr = XGBRegressor()

xgbr.fit(X_train, y_train)

y_pred_xgbr = xgbr.predict(X_test)

In [11]:
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor()

rfr.fit(X_train, y_train)

y_pred_rfr = rfr.predict(X_test)

In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

results = []

models = {
    "AdaBoost           ": (abr, y_pred_abr),
    "Gradient Boosting  ": (gbr, y_pred_gbr),
    "XGBoost            ": (xgbr, y_pred_xgbr),
    "Random Forest      ": (rfr, y_pred_rfr)
}

for name, (_, pred) in models.items():
    results.append({
        "Model": name,
        "MAE": mean_absolute_error(y_test, pred),
        "RMSE": np.sqrt(mean_squared_error(y_test, pred)),
        "R2": r2_score(y_test, pred)
    })

results_df = pd.DataFrame(results)
results_df.sort_values("R2", ascending=False)

                 Model         MAE        RMSE        R2
2  XGBoost              100.641151  162.392128  0.937511
3  Random Forest        106.638793  178.534106  0.924471
1  Gradient Boosting    149.685485  222.861972  0.882309
0  AdaBoost             266.997273  374.584167  0.667516

In [14]:
import pandas as pd

results = [
    {"Model": "XGBoost", "MAE": 100.641151, "RMSE": 162.392128, "R2": 0.937511},
    {"Model": "Random Forest", "MAE": 106.638793, "RMSE": 178.534106, "R2": 0.924471},
    {"Model": "Gradient Boosting", "MAE": 149.685485, "RMSE": 222.861972, "R2": 0.882309},
    {"Model": "AdaBoost", "MAE": 266.997273, "RMSE": 374.584167, "R2": 0.667516},
    {"Model": "Lasso", "MAE": 323.218752, "RMSE": 434.781794, "R2": 0.552065},
    {"Model": "Linear Regression", "MAE": 323.318032, "RMSE": 434.802091, "R2": 0.552023},
    {"Model": "Ridge", "MAE": 323.270691, "RMSE": 434.802482, "R2": 0.552023},
    {"Model": "ElasticNet", "MAE": 322.690681, "RMSE": 441.244457, "R2": 0.538650},
]

results_df = pd.DataFrame(results)

# Sort by R² (highest first)
results_df = results_df.sort_values(by="R2", ascending=False).reset_index(drop=True)

results_df

               Model         MAE        RMSE        R2
0            XGBoost  100.641151  162.392128  0.937511
1      Random Forest  106.638793  178.534106  0.924471
2  Gradient Boosting  149.685485  222.861972  0.882309
3           AdaBoost  266.997273  374.584167  0.667516
4              Lasso  323.218752  434.781794  0.552065
5  Linear Regression  323.318032  434.802091  0.552023
6              Ridge  323.270691  434.802482  0.552023
7         ElasticNet  322.690681  441.244457  0.538650